### ISSUE TITLE
Support for compute engine service credentials

### ISSUE THREAD

**Issue by erlgry** [knq/firebase#1]
Hello,

I was wondering if it is possible to have the library request credentials from compute engine metadata service, when running in the GCE environment? Support for this would remove the need to copy the credential files to the instance.

For example google's lib https://godoc.org/golang.org/x/oauth2/google provides support for ComputeTokenSource. 

Another possibility would be to accept an HTTP Client, so that https://godoc.org/golang.org/x/oauth2/google#DefaultClient instance could be passed to this firebase lib

Thanks

**Comment by kenshaw** [comment]
Yes, you can use any `oauth2.TokenSource` provider using the `firebase.Transport` option and the `oauth2.Transport`:

``` go
    db, err := firebase.NewDatabaseRef(
        firebase.Transport(&oauth2.Transport{
            Source: google.ComputeTokenSource(""),
        }),
    )
```

I will try to add an example showing this, as well as possibly make a better helper option.

**Comment by kenshaw** [comment]
I added a `gce` example just now. I tested it and it works with compute engine credentials as expected. I'll need to think if I want to expose a "simpler" option API to use with `NewDatabaseRef`.

**Comment by erlgry** [comment]
Superb. Thanks @kenshaw

**Comment by erlgry** [comment]
@kenshaw noticed an issue with the GCE example. The 

`log.Fatal(err)`

should be 

```
if err != nil {
   log.Fatal(err)
}

```

Another issue I am running into is that I am always getting a 403 when accessing my firebase DB, as a service account. I haven't been able to figure out why that may be. My compute engine instance is configured to run with the default compute engine service account. Any thoughts on that would be greatly helpful.

**Comment by kenshaw** [comment]
I believe the issue here is that you are missing the correct scopes on the service account you're using. I am writing up some documentation showing what needs to be done to use the `google.ComputeTokenSource`. Also, thanks for the catch there on the err checking. It'll be fixed with the documentation addition.

**Comment by kenshaw** [comment]
I can indeed tell you the issue here is missing the appropriate scope on your compute instance. I just pushed an updated gce example with a `README.md` that shows how to create a compute instance with the necessary scope on the default service account credential.

**Comment by erlgry** [comment]
@kenshaw Thank You so much. That indeed solved the problem. I experimented a bit. And looks like the UserInfo scope is required. I was able to kick off an instance from the UI, assign only the UserInfo scope and then run my go app that no longer ran into the 403.

Again thank you so much. I spent the entire day, trying to figure out what I was doing wrong. Your suggestion did the trick.

**Comment by kenshaw** [comment]
Cool. I just pushed a change that loads the project id (and hence the URL) using the Google compute credentials. I haven't tested it yet, but it should work as expected.

**Comment by erlgry** [comment]
Btw: Turns out I was wrong. The firebase database scope is needed as well (as you documented). For once I thought it was not (still puzzled why).

**Comment by kenshaw** [comment]
The firebase docs definitely state both scopes are needed. My thinking is that the firebase team hasn't fully integrated their backend yet with the Google platform. I'm assuming they'll work those kinks out in the coming months, as well as automatically add the firebase database scope to the default scopes for a compute instance service account. Google has a lot of catchup still in terms of integrating all its cloud products/services, at least in comparison to AWS ...

**Comment by erlgry** [comment]
@kenshaw I am still running into an issue. I am setting up a watch on /users and it appears that something is causing the HTTP client to not follow the redirect. Specifically, I am seeing the following on the console:

```
2016/09/11 11:55:49 GET /users.json HTTP/1.1
Host: myapp.firebaseio.com
User-Agent: Go-http-client/1.1
Accept: text/event-stream
Accept-Encoding: gzip

2016/09/11 11:55:49 HTTP/1.1 307 Temporary Redirect
Access-Control-Allow-Origin: *
Content-Type: text/plain
Location: https://s-usc1c-nss-102.firebaseio.com/users.json?ns=myapp&sse=true
Strict-Transport-Security: max-age=31556926; includeSubDomains; preload
Content-Length: 0
```

Here is my main.go

```
package main

import (
    "fmt"
    "log"
    "net/http"

    "github.com/knq/firebase"
    "golang.org/x/net/context"
)

func main() {

    // create global context
    ctx, cancel := context.WithCancel(context.Background())
    defer cancel()

    // create the DB ref
    db, err := firebase.NewDatabaseRef(
        firebase.GoogleComputeCredentials(""),
        firebase.Log(log.Printf, log.Printf),
    )
    if err != nil {
        log.Fatal(err)
    }

    // start watch
    go startWatch(db.Ref("/users"), ctx)

    http.HandleFunc("/", handle)
    http.HandleFunc("/_ah/health", healthCheckHandler)
    log.Print("Listening on port 8080")
    log.Fatal(http.ListenAndServe(":8080", nil))
}

func handle(w http.ResponseWriter, r *http.Request) {
    if r.URL.Path != "/" {
        http.NotFound(w, r)
        return
    }
    fmt.Fprint(w, "Hello world!")
}

func healthCheckHandler(w http.ResponseWriter, r *http.Request) {
    fmt.Fprint(w, "ok")
}

func startWatch(r *firebase.Ref, ctxt context.Context) {
    log.Printf("starting watch on %s", r.URL().String())
    evs, err := r.Watch(ctxt)
    if err != nil {
        log.Fatal(err)
    }

    for {
        select {
        case e := <-evs:
            if e == nil {
                log.Printf("events channel closed")
                return
            }
            log.Printf("server event: %s", e.String())
        case <-ctxt.Done():
            log.Printf("context done")
            return
        }
    }
}
```

Perhaps I am overlooking something

**Comment by kenshaw** [comment]
The firebase.Log option won't work with Listen/Watch, since it closes the
reader. Remove the Log, and it should work fine. I will try to fix the Log
to work with SSE.

**Comment by erlgry** [comment]
Thanks. That did the trick
