### ISSUE TITLE
Additional dependencies?

### ISSUE THREAD

**Issue by m00sey** [knq/firebase#2]
Hi, 

I'm trying to get up and running, however after running `go get -u github.com/knq/firebase`

then trying to build my existing application I  get an error:

`FATAL: command "build" failed: failed to resolve import path "cloud.google.com/go/bigquery": import "google.golang.org/api/bigquery/v2": not found: stat /Users/kg/project/src/google.golang.org/api/bigquery/v2: no such file or directory`

**Comment by kenshaw** [comment]
I believe you need to install those dependencies too. No idea why they wouldn't have been retrieved / updated with the original `go get -u` command. Just simply install those packages via `go get`:
```sh
$ go get -u google.golang.org/api/bigquery/v2
```
Not sure why this is a dependency, but it must be a dependency of one of the Google packages (maybe `metadata`) that this uses for retrieving credentials in the app engine environment.
