### ISSUE TITLE
Help implementing firebase helpers

### ISSUE THREAD

**Issue by sheerun** [knq/firebase#3]
Hey,

I've started a project to impelment firebase helpers that can be used with events firebase sends. Currently I wrote support for Put and Patch, but it doesn't handle arrays yet.

Would you mind to help to finish it? To write extra tests and array support.

https://github.com/sheerun/firebasehelpers

**Comment by sheerun** [comment]
I intended to send PR to integrate it with this project, but array support is a blocker ;/

**Comment by kenshaw** [comment]
I really don't understand what the request is.
