### ISSUE TITLE
Signing in with custom JWT token

### ISSUE THREAD

**Issue by sheerun** [knq/firebase#4]
Is it possible? Like described here: https://firebase.google.com/docs/auth/admin/create-custom-tokens

**Comment by kenshaw** [comment]
Yes.

On Apr 11, 2017 9:22 PM, "Adam Stankiewicz" <notifications@github.com>
wrote:

Is it possible? Like described here: https://firebase.google.com/
docs/auth/admin/create-custom-tokens

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/knq/firebase/issues/4>, or mute the thread

**Comment by sheerun** [comment]
Could you show how? I cannot figure out

**Comment by sheerun** [comment]
Specifically I search for an equivalent of signInWithCustomToken

**Comment by kenshaw** [comment]
Copied/pasted from `example/full/main.go`:

```go
	// create authenticated "admin" ref
	adminDB := db.Ref("/people")
	firebase.DefaultQueryOptions(
		firebase.AuthOverride(map[string]interface{}{
			"uid":   "<admin>",
			"admin": true,
		}),
	)(adminDB)

	// retrieve a shallow map (ie, the keys) using the admin ref
	log.Printf("retrieving all keys as admin")
	keys := make(map[string]interface{})
	err = adminDB.Get(&keys, firebase.Shallow)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("admin retrieved keys: %+v", keys)
```

Please note there are a number of other ways to also accomplish this via the login, but it requires understanding how the custom authentication tokens are generated, and which I do not have time to cover here. It wouldn't take more than a couple hours of research on Firebase's APIs, however, and looking through the GoDoc for this package to put the two together. Understand that this implementation of Firebase is not an attempt to recreate the *client* APIs for Firebase, but to provide comprehensive *server* APIs. Unfortunately, there is no official Go API provided for Firebase, and in my opinion, the other Firebase APIs that existed when this was written, did not provide comprehensive support for the basic Firebase features in what I would call the "Go-way".
